### ISSUE TITLE
Subtask: Tasks for TODO list before release

### ISSUE THREAD

**Issue by jaslatendresse** [compgirl123/TutifySoen490#126]
Subtask of #100

- [x] Remove the add button from the notifications

- [x] Add delete button for notifications

- [x] Add tests for delete todo (Look into redux tests)
