### ISSUE TITLE
Subtask: Delete uploaded documents, Tutor View Individual File Uploads to Students, View Latest Doc, Padding Fix

### ISSUE THREAD

**Issue by kasthurie** [compgirl123/TutifySoen490#133]
SubTask of #37 

- [x] As a tutor, I would like to be able to delete the documents uploaded for one student. (Claudia)

- [x] As a tutor, I would like to be able to delete the documents uploaded for many students. (Claudia , Wait for Pierre's function for it).
- [x] Add reload function (Kasthurie).

- [x] As a tutor, i would like to see the uploaded documents for my individual students (Claudia).

- [x] As both a tutor and a student, I would want to have a cleaner view with button padding for documents view (Kasthurie).

- [x] As a tutor, I would like to see my latest doc on upload document page (Kasthurie).

- [x] Clean code, ex: delete unused code(Kasthurie + Claudia). (2)

- [x] Fixing issues in user_controller with Object Keys function. Use req.session instead. (Claudia)

- [x] Fixing Issues with ViewTutorCourse and ViewCoursePage. Filtering by Course id rather than name for security reasons and combining these two pages together.

- [x] UI fixes 

     - Redirect the upload doc button on profile page to select course page, change it to one button (Kasthurie) 
     - Fix padding on individual documents shared pages (Kasthurie) 
     - Redirect message button to announcements page (Kasthurie)
     - Remove garbage button on the last column of all documents (Kasthurie)
     - Hide Document button when no documents are uploaded in doclist.js (Claudia)

Unit Tests:
Students:

https://github.com/compgirl123/TutifySoen490/blob/master/tutify/test/listofdocuments-tests-students.spec.js

Tutors:

https://github.com/compgirl123/TutifySoen490/blob/master/tutify/test/listofdocuments-tests-tutors.spec.js

Priority: High
Risk: Medium
Points: 13
