### ISSUE TITLE
SubTask : Share Document Feature Fixes

### ISSUE THREAD

**Issue by compgirl123** [compgirl123/TutifySoen490#138]
Subtask of #36 

- [x] Making checkbox work. (2)
- [x] Allowing Many students to be selected in order to send documents individually to many students. (end) (3)
- [x] Fixing issue with routing, dont show /:file when selecting My Students
-  [x] Adding a column in /doclist that displays the class the document is shared to or if it has not been shared to a class (4)
-  [x] Fixing the date uploaded in /doclist that displays date of uploaded document. Please format the date correctly so we could see it in a clean format with date and time (5)
- [x] Adding the actual tutor name instead of tutor id in the Column
- [x] Query by email not by first and last name for the share to classes and individual students. (1)

Priority: High
Risk: Medium
Points: 13
