### ISSUE TITLE
For Release 2 

### ISSUE THREAD

**Issue by jaslatendresse** [compgirl123/TutifySoen490#139]
- CODE CLEAN UP (Profile especially, check session, formatting, naming conventions, comments) 
- Testing 
- Deployment (Jasmine + Cynthia) 
- Frontend fixes to make it consistent across the whole app
- Add logs

**Features:**
Tanya & Bilal:
- [x] Tutors can select and add courses #142 

Claudia & Kasthurie:
- [x] Delete docs #133  
- [x] Tutor can see docs shared individually #133  
- [x] Link tasks to their stories
- [x] Add comments to the frontend and make sure enough comments to backend
- [x] Testing for upload doc #135  
- [x] Mockups for upload doc new pages
- [x] Add logs to our code
- [x] Tasks mentioned in issue #133

Jasmine & Cynthia:
- [x] Delete notification #140 
- [x] Tutor can update their bio/description #146
