### ISSUE TITLE
Task for release 2

### ISSUE THREAD

**Issue by jaslatendresse** [compgirl123/TutifySoen490#149]
- [x] Add logs to our code (to functions) 

- [x] #135 Add tests for delete todo and delete notif

- [x] #148 Fix view courses for deployment 

- [x] #124 Add resources to the resource page 

- [x] #37 Change frontend for upload documents (branch: subtask/student-page-view)

- [x] Update milestone document

- [x] Update wiki about deployment

- [x] Redeploy with updated version of app
