### ISSUE TITLE
Subtask US 24 - Front-End

### ISSUE THREAD

**Issue by compgirl123** [compgirl123/TutifySoen490#172]
Subtask of #168 

Front-End Pages Design:

- [x]  Page for Students to Submit Documents to Tutor (kept the same page)

- [x]  Add a Tab to switch view

- [x] Added if-else statement to view tab depending if its a tutor or a student

- [x]  Add links to the tab to view pages
