### ISSUE TITLE
Subtask : Bug Fixes on Quiz Page + Ability to Add new quiz + Grading page

### ISSUE THREAD

**Issue by compgirl123** [compgirl123/TutifySoen490#205]
As a tutor, I would like to have the ability to add quizzes for each of my students and classes.
I would also like to have an appropriate working display for my quiz page as well.

- [x] Fixing Bugs with Blank Page display on the quiz page.
- [x] Fixing Bugs with take quiz page thus adding features such as color indicators for answers as well as coordination of the questions with database answers
- [x] Fixing Bugs with model 
- [x] Adding "Add Quiz" Button Functionality. Adding ability to add: 
          - Front-end: Kasthurie and Claudia
          - Backend: Pierre
- [x] Share quizzes to certain classes with students.
        - Front-end : Claudia and Kasthurie
        - Backend : Pierre
- [x] View Quiz on student page filtered by courses and tutors : Claudia
- [x] Added a grade page where students can view the points they have earned upon completion of quizes: Claudia and Kasthurie
- [x] Unit testing for Quiz and Video feature: Pierre

Subtask of #192 

Priority: High
Risk: Low
Points: 13
