### ISSUE TITLE
US 32 - Tutor public profile page

### ISSUE THREAD

**Issue by cynthiac3** [compgirl123/TutifySoen490#208]
As a tutor, I want to have a public profile page that people can access without being logged in and that can be shared to social medias.

**Tasks**
- [x] Create route to access tutor profile page
- [x] Create class component that will contain the tutor information
- [x] Create component user info page that contains the tutor user info (1) 
- [x] Create component display subjects of current tutor (2) 
- [x] Create component display courses of current component (3) 
- [x] Fetch tutor description, tutor info, profile picture, courses and subjects from db
- [x] Fetch tutor email from db (through account)
- [x] Redirect to 404 if put a non-existing id instead of showing undefined fields 

(1) Cannot reuse current user info component because it relies on check session to display information and it contains too many component. Conditional rendering would require major refactoring. 
(2) Same as above
(3) Same as above 

Unit test:
https://github.com/compgirl123/TutifySoen490/blob/master/tutify/test/tutor-public-profile.spec.js

Priority: High
Risk: Low
Points: 8
