### ISSUE TITLE
Subtask : Bug Fixes on Quiz Page + points and attempts fixes 

### ISSUE THREAD

**Issue by kasthurie** [compgirl123/TutifySoen490#220]
As a tutor, I would like to have the ability to add points to each questions of a quiz and only see the points of the last attempt on the grades page. 

Subtask of #192  

**Backend** : Pierre and Claudia

- [x] Multiple attempts should not be counted multiple times in the grades page

- [x] Refactor points and connect it with the badges

**Frontend** : Kasthurie and Claudia

- [x] Add check fields for the dialog forms

- [x] Fix position of Add Question button 

- [x] Fix screen display size in questions.js page 

- [x] Ability to delete entire quizzes (backend also)

- [x] Ability to edit quizzes by deleting questions (backend also)

- [x] Add Total points for each student

Priority: High
Risk: Medium
Points: 8
