### ISSUE TITLE
Subtask : Badge feature enhancement

### ISSUE THREAD

**Issue by kasthurie** [compgirl123/TutifySoen490#221]
As a student, I would like to unlock badges as rewards for points accumulated by taking quizzes.

- [x] Unlock badges with points accumulated for.
- [x] Make the feature work with the quiz points .
- [x] Update help button for the student to show how point system works.

Subtask of #207 

Priority: High
Risk: Medium
Points: 8
