### ISSUE TITLE
Release 3 Checklist

### ISSUE THREAD

**Issue by kasthurie** [compgirl123/TutifySoen490#222]
- [x] Complete the issues assigned for Sprint 13 (Quiz + Badges, bugs, unit testing, etc)

- [x] Code cleanup

- [x] Making sure all subtasks are linked to their main issues

- [x] Making sure all pull requests are linked to their issues

- [x] Making sure all issues have complete breakdown of tasks

- [x] Create an issue and ask stakeholders to answer them, put the issue no. in milestone doc

- [x] Acceptance testing, and mockups for all user stories 

- [x] Update Diagrams and list important source code file paths on Milestone Document

- [x] Finish containerization

- [x] 15 minutes video presentation (walkthrough of all new features from Release 3, and pick 3 features from last deliverable to show the pr, issue description, testing, mockups, etc)

- [x] 2 min video to summarize our project and represent our team (logo, project summary, team members)
