### ISSUE TITLE
Unit Testing For Sprint 13 Features

### ISSUE THREAD

**Issue by compgirl123** [compgirl123/TutifySoen490#223]
As a developer, I would like to write unit tests to test the functionality of our features.

- [x] Unit testing Quiz feature #220 
Link to test files:
https://github.com/compgirl123/TutifySoen490/blob/master/tutify/test/quiz-tests.spec.js
https://github.com/compgirl123/TutifySoen490/blob/master/tutify/test/quiz-list-tests.spec.js

- [x] Unit testing Badge feature #221 
Link to test file:
https://github.com/compgirl123/TutifySoen490/blob/master/tutify/test/trophies-tests.spec.js
- [x] Unit testing Tutor Public Profile #227 
Link to test file:
https://github.com/compgirl123/TutifySoen490/blob/master/tutify/test/tutor-public-profile.spec.js

Points : 8
Risk: Medium
Priority: High
